### ISSUE TITLE
Accurate sizes: Image block with center alignment gets wrong sizes

### ISSUE THREAD

**Issue by mukeshpanchal27** [WordPress/performance#1725]
## Summary

When the Image block is set to `center` alignment, it is constrained by its intrinsic width. However, it should instead be constrained by the contentSize as specified in the CSS.

When image block sets with the `center` alignment it constrained by `contentSize` but per current implementation it constrained by image width that needs to be correct.

Core CSS that apply when `center` alignment sets:
```css
.is-layout-constrained > :where(:not(.alignleft):not(.alignright):not(.alignfull)) {
    max-width: var(--wp--style--global--content-size);
    margin-left: auto !important;
    margin-right: auto !important;
}
```

## Steps to Reproduce:

1. Insert an Image block into a post or page.
2. Set the image alignment to `center`.
3. Observe that the image width is not properly constrained by the contentSize defined in the theme.

![Image](https://github.com/user-attachments/assets/762ad4b1-1e13-4bc6-a79a-b5a1c0027214)
