### ISSUE TITLE
Bump tested up to WordPress version to 6.8

### ISSUE THREAD

**Issue by felixarntz** [WordPress/performance#1960]
This issue is about two related things:
1. Bump all `readme.txt` tested up to WordPress versions to 6.8.
2. Simplify deploying such a change to WordPress.org without having to publish an actual release.

The first point is obviously very easy and quick. But the second point addresses a problem we've been having: It's an odd requirement to have to publish a release just to bump the "Tested up to" WordPress version.

So let's think about how we can implement the second point:
* There's the https://github.com/10up/action-wordpress-plugin-asset-update GitHub action, which we should probably use for this.
* Since we have multiple plugins, we cannot just use the simple example workflow as listed in that project's readme - instead we have to integrate it without monorepo structure, similarly how we already do in the actual plugin release deployment workflow.
* Ideally this GitHub workflow would not be triggered by a regular GitHub process, but rather via manual `workflow_dispatch`. Here's why: We don't necessarily want _any_ screenshot, banner, icon, or `readme.txt` change to be immediately deployed to WordPress.org. For example, if you update a readme to refer to a new plugin feature that it's only going to be available in the next release. Therefore it's safer to deploy manually.
    * It should be possible to either run this for all plugins, or for a specific plugin.
    * Ideally, any plugin should only have their assets deployed if the plugin's "Tested up to" version is higher than the "Tested up to" version from the `readme.txt` that is currently deployed to .org.
* What would be super neat would be to not just deploy any updated assets, but rather _only_ modify the "Tested up to" version in the `readme.txt` file from the version that is already deployed to WordPress.org. That would make it 100% safe that no other change in the `readme.txt` could accidentally be deployed preliminarily.
    * I realize though that implementing this would take extra effort, since it would require more manual work than just deploying entire files from the GitHub repository as-is.
    * So I consider this a stretch goal, which we could also consider further down the road as a v2. I think a manual `workflow_dispatch` GitHub workflow would work quite well for a start.

**Comment by felixarntz** [comment]
@westonruter @swissspidy @b1ink0 @ShyamGadde Curious to get your thoughts on which approach we should take for this.

**Comment by swissspidy** [comment]
It seems relatively straightforward to add a new workflow that runs `10up/action-wordpress-plugin-asset-update` for all or some of the plugins.

The stretch goal seems overkill to me, so I would not worry about that for now.

And with the new release cadence I wouldn't spend too much time on this anyway... Could either push a new release next month or even do it manually, and then put this in the backlog until 6.9 is coming up.

**Comment by felixarntz** [comment]
> The stretch goal seems overkill to me, so I would not worry about that for now.

I don't think it's overkill, it's indeed a stretch goal. In other words: If we had infinite time on our hands, this would certainly be a good thing to have I think. But I agree with you it's probably going to take too much time to be worth the effort.

**Comment by westonruter** [comment]
> The first point is obviously very easy and quick. But the second point addresses a problem we've been having: It's an odd requirement to have to publish a release just to bump the "Tested up to" WordPress version.

We don't have to actually publish a release, right? In the past I've just manually updated the `readme.txt` in the SVN tag. Granted this is not ideal, but it gets the job done.

**Comment by felixarntz** [comment]
Right, I meant we'll have to publish a release to do it without manually touching SVN stuff - neither of which is ideal.

**Comment by ShyamGadde** [comment]
I've been exploring the stretch goal mentioned in the issue—modifying _only_ the "Tested up to" version in the WordPress.org `readme.txt` without changing anything else.

The approach I came up with works as follows:
1. Download the current `readme.txt` from WordPress.org SVN
2. Extract the "Tested up to" version from both the repo and WordPress.org `readme.txt` files
3. If our version is higher, copy the WordPress.org readme to the plugin directory and update _only_ the "Tested up to" version
4. Use `action-wordpress-plugin-asset-update` to push this modified file

Here's the key part of the implementation:

```sh
# Get the latest readme.txt from WordPress.org
curl -s -o /tmp/wp-org-readme.txt "https://plugins.svn.wordpress.org/${{ matrix.plugin }}/trunk/readme.txt"

# Extract versions for comparison
WP_ORG_VERSION=$(grep -E "^Tested up to:" /tmp/wp-org-readme.txt | sed -E 's/Tested up to:[[:space:]]*([0-9.]+)/\1/')
REPO_VERSION=$(grep -E "^Tested up to:" ./plugins/${{ matrix.plugin }}/readme.txt | sed -E 's/Tested up to:[[:space:]]*([0-9.]+)/\1/')

# Only if our version is higher
if [ "$WP_ORG_VERSION" != "$REPO_VERSION" ]; then
  # Use the WordPress.org readme as the base to ensure no unintended changes
  cp /tmp/wp-org-readme.txt ./plugins/${{ matrix.plugin }}/readme.txt
  # Update only the "Tested up to" version
  sed -i -E 's/^(Tested up to:)[[:space:]]*[0-9.]+/\1 '"$REPO_VERSION"'/' ./plugins/${{ matrix.plugin }}/readme.txt
fi
```

This approach ensures:
- We only update the "Tested up to" version and nothing else
- No other potential changes in our local readme.txt are accidentally deployed

For reference, here’s the full workflow file I was experimenting with:
<details> 

<summary>Complete workflow file</summary>

```yaml
name: Bump WordPress Compatibility Version

on:
  workflow_dispatch:
    inputs:
      plugin:
        type: string
        description: 'Plugin slug (leave empty for all plugins)'
        required: false

jobs:
  prepare-matrix:
    name: Prepare plugins matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.plugins }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure plugin matrix
        id: set-matrix
        run: |
          PLUGINS=$(jq -r '.plugins' plugins.json)
          if [[ -n "${{ inputs.plugin }}" ]]; then
            SLUG="${{ inputs.plugin }}"
            if echo $PLUGINS | jq -e '.[] | select(. == "'$SLUG'")' > /dev/null; then
              PLUGINS="[ \"$SLUG\" ]"
            else
              echo "::error::Plugin '$SLUG' not found in plugins.json"
              exit 1
            fi
          fi
          echo "::notice::Updating plugins: $(echo ${PLUGINS[@]})"
          echo "plugins=$(echo $PLUGINS | jq -c .)" >> $GITHUB_OUTPUT

  update-compatibility:
    name: Update ${{ matrix.plugin }} compatibility
    needs: prepare-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        plugin: ${{ fromJSON(needs.prepare-matrix.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compare versions
        id: version-compare
        run: |
          # Get WordPress.org version.
          curl -sSL --retry 3 --retry-delay 5 --retry-all-errors --fail -o /tmp/wp-org-readme.txt "https://plugins.svn.wordpress.org/${{ matrix.plugin }}/trunk/readme.txt"
          if [ $? -ne 0 ]; then
            echo "::error::Could not fetch readme from WordPress.org for ${{ matrix.plugin }}"
            exit 1
          fi

          WP_ORG_VERSION=$(grep -E "^Tested up to:" /tmp/wp-org-readme.txt | sed -E 's/Tested up to:[[:space:]]*([0-9.]+)/\1/')
          REPO_VERSION=$(grep -E "^Tested up to:" ./plugins/${{ matrix.plugin }}/readme.txt | sed -E 's/Tested up to:[[:space:]]*([0-9.]+)/\1/')

          echo "wp_org_version=$WP_ORG_VERSION" >> $GITHUB_OUTPUT
          echo "repo_version=$REPO_VERSION" >> $GITHUB_OUTPUT

          if [ "$WP_ORG_VERSION" = "$REPO_VERSION" ]; then
            echo "Versions match ($WP_ORG_VERSION). No update needed."
            echo "needs_update=false" >> $GITHUB_OUTPUT
          else
            echo "Version mismatch: WordPress.org=$WP_ORG_VERSION, Repo=$REPO_VERSION"
            echo "needs_update=true" >> $GITHUB_OUTPUT
          fi

      - name: Prepare and update readme
        if: steps.version-compare.outputs.needs_update == 'true'
        run: |
          # Replace local readme with WordPress.org version, updating only compatibility.
          cp /tmp/wp-org-readme.txt ./plugins/${{ matrix.plugin }}/readme.txt
          sed -i -E 's/^(Tested up to:)[[:space:]]*[0-9.]+/\1 ${{ steps.version-compare.outputs.repo_version }}/' ./plugins/${{ matrix.plugin }}/readme.txt

          # Show the diff of what's being updated.
          echo "Changes made to readme.txt:"
          diff -u /tmp/wp-org-readme.txt ./plugins/${{ matrix.plugin }}/readme.txt || true

      - name: Push to WordPress.org
        if: steps.version-compare.outputs.needs_update == 'true'
        uses: 10up/action-wordpress-plugin-asset-update@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: ${{ matrix.plugin }}
          SKIP_ASSETS: true
          IGNORE_OTHER_FILES: true

```

</details>

I haven't been able to test the actual WordPress.org update part, but the workflow seems to correctly identify plugins that need updates and makes only the necessary changes to the readme file.
