### ISSUE TITLE
Configure `DRY_RUN` to Github Action

### ISSUE THREAD

**Issue by mukeshpanchal27** [WordPress/performance#734]
## Bug Description
Follow-up issue for https://github.com/WordPress/performance/pull/710#issuecomment-1540592224

The [10up deploy action](https://github.com/10up/action-wordpress-plugin-deploy/releases/tag/2.2.0) officially support `DRY_RUN` mode that can be used while testing this action.

```
- name: WordPress Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      with:
        dry-run: true
```
